/**
 * Helper to escape CSV cell content
 */
function escapeCSV(val: any): string {
  if (val === null || val === undefined) return '""';
  const str = String(val);
  return `"${str.replace(/"/g, '""')}"`;
}

/**
 * Exports an array of objects to a CSV file with UTF-8 BOM so Excel opens Bengali correctly.
 */
export function exportToCSV(filename: string, data: any[], headers?: string[]): void {
  if (!data || data.length === 0) return;

  const actualHeaders = headers || Object.keys(data[0]);
  const headerRow = actualHeaders.map((h) => escapeCSV(h)).join(',');

  const rows = data.map((item) =>
    actualHeaders
      .map((header) => {
        const val = item[header] !== undefined ? item[header] : '';
        return escapeCSV(val);
      })
      .join(',')
  );

  const csvContent = '\uFEFF' + [headerRow, ...rows].join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export interface MultiSectionMeta {
  institution: string;
  reportTitle: string;
  branch: string;
  monthYear: string;
  generatedAt: string;
  generatedBy: string;
}

export interface MultiSectionSection {
  title: string;
  data: any[];
  headers: string[];
  summaryRow?: Record<string, any>;
}

/**
 * Exports multiple sections formatted nicely into a single CSV with UTF-8 BOM
 */
export function exportMultiSectionExcel(
  filename: string,
  meta: MultiSectionMeta,
  sections: MultiSectionSection[]
): void {
  const lines: string[] = [];

  // Metadata Header Block
  lines.push(escapeCSV(meta.institution));
  lines.push(escapeCSV(meta.reportTitle));
  lines.push(`"Branch / Campus:",${escapeCSV(meta.branch)},"Billing Period:",${escapeCSV(meta.monthYear)}`);
  lines.push(`"Generated On:",${escapeCSV(meta.generatedAt)},"Generated By:",${escapeCSV(meta.generatedBy)}`);
  lines.push('""'); // empty line separator

  // Iterate sections
  sections.forEach((sec) => {
    lines.push(escapeCSV(`=== ${sec.title} ===`));
    lines.push(sec.headers.map((h) => escapeCSV(h)).join(','));

    sec.data.forEach((row) => {
      const rowLine = sec.headers
        .map((h) => {
          const val = row[h] !== undefined ? row[h] : '';
          return escapeCSV(val);
        })
        .join(',');
      lines.push(rowLine);
    });

    if (sec.summaryRow) {
      const summaryLine = sec.headers
        .map((h) => {
          const val = sec.summaryRow![h] !== undefined ? sec.summaryRow![h] : '';
          return escapeCSV(val);
        })
        .join(',');
      lines.push(summaryLine);
    }

    lines.push('""'); // empty line between sections
  });

  const csvContent = '\uFEFF' + lines.join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
